---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: science-platform
  namespace: default
spec:
  interval: 1m
  url: https://images.opencadc.org/chartrepo/platform
