apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: science-platform
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: base
      version: "0.3.3"
      sourceRef:
        kind: HelmRepository
        name: science-platform
      interval: 1m
